version: "2"

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosec
    - ineffassign
    - gocritic
    - usestdlibvars
    - unused
    - misspell

  settings:
    govet:
      enable-all: true
    gocritic:
      disabled-checks:
        - unslice

issues:
  exclude-rules:
    # Relax errcheck and gosec in test files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
